workflows: package-rpm: improve Bash script readability
Improve the readability of various Bash scripts within the workflow by
encasing variable names in braces when used.

Signed-off-by: James Hershaw <james.hershaw@corigine.com>
Reviewed-by: Walter Heymans <walter.heymans@corigine.com>
Signed-off-by: Louis Peens <louis.peens@corigine.com>

diff --git a/.github/workflows/package-rpm.yaml b/.github/workflows/package-rpm.yaml
--- a/.github/workflows/package-rpm.yaml
+++ b/.github/workflows/package-rpm.yaml
@@ -666,16 +666,16 @@ jobs:
 
           if [[ "${{ matrix.release.upload_dir }}" == "openeuler"* || \
                 "${{ matrix.release.upload_dir }}" == "kylinos"* ]]; then
-            new_dependencies="$( echo "${dependencies[$package_manager]}" | \
+            new_dependencies="$( echo "${dependencies[${package_manager}]}" | \
                                  sed 's/elfutils-libelf-devel/elfutils-devel/' )"
-            dependencies[$package_manager]="$new_dependencies"
+            dependencies[${package_manager}]="${new_dependencies}"
           fi
 
-          prerequisites="${dependencies[$package_manager]}"
+          prerequisites="${dependencies[${package_manager}]}"
           provision="false"
-          for package in $prerequisites; do
-            if ! $(echo "$installed_packages" | grep -w -q "$package"); then
-              missing_deps=$missing_deps$package" "
+          for package in ${prerequisites}; do
+            if ! $(echo "${installed_packages}" | grep -w -q "${package}"); then
+              missing_deps=${missing_deps}${package}" "
               provision="true"
             fi
           done
@@ -686,8 +686,8 @@ jobs:
             azcopy_present="false"
           fi
 
-          echo "missing_deps=$missing_deps" | tee -a $GITHUB_OUTPUT
-          echo "provision=$provision" | tee -a $GITHUB_OUTPUT
+          echo "missing_deps=${missing_deps}" | tee -a $GITHUB_OUTPUT
+          echo "provision=${provision}" | tee -a $GITHUB_OUTPUT
           echo "azcopy_present=${azcopy_present}" | tee -a $GITHUB_OUTPUT
 
       - name: Add pre-requisite repositories and plugins | CentOS-8
@@ -793,14 +793,14 @@ jobs:
           else
             BASE_DIR=binaries/nfp-drv-dkms/${{ inputs.driver_build_type }}
           fi
-          echo "BASE_DIR=$BASE_DIR" | tee -a $GITHUB_ENV
+          echo "BASE_DIR=${BASE_DIR}" | tee -a $GITHUB_ENV
 
           DOWNLOAD=$(pwd)/.download/
-          echo "DOWNLOAD=$DOWNLOAD" | tee -a $GITHUB_ENV
-          mkdir -p $DOWNLOAD
+          echo "DOWNLOAD=${DOWNLOAD}" | tee -a $GITHUB_ENV
+          mkdir -p ${DOWNLOAD}
           UNPACKED=$(pwd)/.unpacked/
-          echo "UNPACKED=$UNPACKED" | tee -a $GITHUB_ENV
-          mkdir -p $UNPACKED
+          echo "UNPACKED=${UNPACKED}" | tee -a $GITHUB_ENV
+          mkdir -p ${UNPACKED}
 
       - name: Install azcopy binary
         if: >-
@@ -812,7 +812,7 @@ jobs:
             binary_link=https://aka.ms/downloadazcopy-v10-linux
           fi
 
-          wget $binary_link -O /tmp/downloadazcopy-v10-linux.tgz
+          wget ${binary_link} -O /tmp/downloadazcopy-v10-linux.tgz
           tar -xvf /tmp/downloadazcopy-v10-linux.tgz -C /tmp/ --strip-components=1
           sudo cp /tmp/azcopy /usr/bin/
 
@@ -840,11 +840,11 @@ jobs:
           DRIVER_VER=${DRIVER_TAR%.tgz}
           RPM_TAR=${DRIVER_VER%-*}
 
-          tar xvfz ${{ env.DOWNLOAD }}/$DRIVER_TAR -C ${{ env.UNPACKED }}
+          tar xvfz ${{ env.DOWNLOAD }}/${DRIVER_TAR} -C ${{ env.UNPACKED }}
 
-          echo "DRIVER_TAR=$DRIVER_TAR" | tee -a $GITHUB_ENV
-          echo "DRIVER_VER=$DRIVER_VER" | tee -a $GITHUB_ENV
-          echo "RPM_TAR=$RPM_TAR.tgz" | tee -a $GITHUB_ENV
+          echo "DRIVER_TAR=${DRIVER_TAR}" | tee -a $GITHUB_ENV
+          echo "DRIVER_VER=${DRIVER_VER}" | tee -a $GITHUB_ENV
+          echo "RPM_TAR=${RPM_TAR}.tgz" | tee -a $GITHUB_ENV
 
       - name: Download Kernel Header Packages | Mirror
         if: matrix.release.mirror != 'local'
@@ -877,11 +877,11 @@ jobs:
           mkdir -p kernels
           VERSIONS=$(ls ./ | grep "linux-.*[0-9]$")
 
-          for SOURCE in $VERSIONS; do
-            find $(pwd)/$SOURCE-obj/x86_64/default/ -maxdepth 1 -mindepth 1 -not -name Makefile \
-              -exec cp -r {} $(pwd)/$SOURCE/ \;
+          for SOURCE in ${VERSIONS}; do
+            find $(pwd)/${SOURCE}-obj/x86_64/default/ -maxdepth 1 -mindepth 1 -not -name Makefile \
+              -exec cp -r {} $(pwd)/${SOURCE}/ \;
 
-            mv $(pwd)/$SOURCE/ $(pwd)/kernels/$SOURCE
+            mv $(pwd)/${SOURCE}/ $(pwd)/kernels/${SOURCE}
           done
 
       - name: Build RPM packages
@@ -891,12 +891,12 @@ jobs:
 
           for HEADERS in $(ls ${{ env.UNPACKED }}/usr/src/kernels/); do
             rpmbuild \
-              -D "%kernel_path ${{ env.UNPACKED }}/usr/src/kernels/$HEADERS/" \
-              -D "_topdir /tmp/$TARGET_DISTRO/${{ env.DRIVER_VER }}/rpmbuild" \
+              -D "%kernel_path ${{ env.UNPACKED }}/usr/src/kernels/${HEADERS}/" \
+              -D "_topdir /tmp/${TARGET_DISTRO}/${{ env.DRIVER_VER }}/rpmbuild" \
               -tb ${{ env.UNPACKED }}/${{ env.DRIVER_VER }}/${{ env.RPM_TAR }}
           done
 
-          RPM_DIR=/tmp/$TARGET_DISTRO/${{ env.DRIVER_VER }}/rpmbuild/RPMS/${{ matrix.release.arch }}
+          RPM_DIR=/tmp/${TARGET_DISTRO}/${{ env.DRIVER_VER }}/rpmbuild/RPMS/${{ matrix.release.arch }}
           echo "RPM_DIR=${RPM_DIR}/*" | tee -a $GITHUB_ENV
           echo "TARGET_DISTRO=${TARGET_DISTRO}" | tee -a $GITHUB_ENV
 
@@ -908,13 +908,13 @@ jobs:
 
           if [[ '${{ inputs.driver_upload_location }}' == 'tmp' || \
                 '${{ inputs.driver_build_type }}' == 'tmp' ]]; then
-            AZURE_PATH=tmp/nfp_drv_dkms_builds/${{ github.actor }}/$DATE/rpm/${{ env.TARGET_DISTRO }}
+            AZURE_PATH=tmp/nfp_drv_dkms_builds/${{ github.actor }}/${DATE}/rpm/${{ env.TARGET_DISTRO }}
           else
             RELEASE_VER_MAJOR=$(echo ${{ env.RPM_TAR }} | \
               sed 's/agilio-nfp-driver-\([0-9]\{2\}\.[0-9]\{2\}\).*/\1/' )
-            AZURE_PATH=${{ env.BASE_DIR }}/$RELEASE_VER_MAJOR/rpm/${{ env.TARGET_DISTRO }}
+            AZURE_PATH=${{ env.BASE_DIR }}/${RELEASE_VER_MAJOR}/rpm/${{ env.TARGET_DISTRO }}
           fi
-          echo "AZURE_PATH=$AZURE_PATH" | tee -a $GITHUB_ENV
+          echo "AZURE_PATH=${AZURE_PATH}" | tee -a $GITHUB_ENV
 
       - name: Upload RPM packages
         uses: Corigine/ci-libs/github_actions/azure/azcopy_upload_sync@main
